In [1]:
import gym
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, InputLayer
from keras.optimizers import Adam
from keras.losses import CategoricalCrossentropy
from keras.initializers import GlorotUniform
import numpy as np



In [28]:
model = Sequential()
model.add(InputLayer(input_shape=(2,)))
model.add(Dense(units=20, name='dense1', activation='relu',
                kernel_initializer=GlorotUniform(seed=0),
                bias_initializer=GlorotUniform(seed=0)))
model.add(Dense(units=10, name='dense2', activation='relu',
                kernel_initializer=GlorotUniform(seed=0),
                bias_initializer=GlorotUniform(seed=0)))
model.add(Dense(units=2, name='output', activation='softmax',
                kernel_initializer=GlorotUniform(seed=0),
                bias_initializer=GlorotUniform(seed=0)))

optimizer = Adam(lr=0.01)
model.compile(optimizer=optimizer, loss=CategoricalCrossentropy())

model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense1 (Dense)               (None, 20)                60        
_________________________________________________________________
dense2 (Dense)               (None, 10)                210       
_________________________________________________________________
output (Dense)               (None, 2)                 22        
Total params: 292
Trainable params: 292
Non-trainable params: 0
_________________________________________________________________


In [29]:
n_sample = 10
state_dim = 2
n_acts = 2
states = np.random.rand(n_sample, state_dim)
actions = np.random.randint(n_acts, size=n_sample)
g = np.random.randint(-5, 20, size=n_sample)
print(states)
print(actions)
print(rewards)

[[0.34069657 0.30442519]
 [0.46586286 0.06145329]
 [0.18949442 0.88524063]
 [0.37604    0.82132802]
 [0.47283945 0.75271028]
 [0.41395348 0.6479495 ]
 [0.34863531 0.14091377]
 [0.52386693 0.90595216]
 [0.55111651 0.10825176]
 [0.62558227 0.21719061]]
[1 0 1 1 0 1 0 0 0 1]
[-4  6  7 16 -3 16 13  3 10 -3]


In [33]:
model(states)

<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[0.21671697, 0.78328305],
       [0.23004137, 0.7699587 ],
       [0.22409762, 0.7759024 ],
       [0.20887823, 0.79112184],
       [0.20217721, 0.7978228 ],
       [0.20362702, 0.79637295],
       [0.22701724, 0.7729827 ],
       [0.20202471, 0.79797524],
       [0.2254989 , 0.77450114],
       [0.21690542, 0.7830946 ]], dtype=float32)>

In [41]:
tf.math.log(
    tf.reduce_max(model(states) * tf.one_hot(actions, 2), axis=1)
) * g

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([ -2.6868725 ,  -1.4694961 ,  -0.        ,   0.2343033 ,
       -28.774992  ,  -0.68306303,  -7.4136467 ,  -6.397461  ,
       -11.91552   ,  -3.1785233 ], dtype=float32)>

In [43]:
g

array([11,  1,  0, -1, 18,  3,  5,  4,  8, 13])

In [42]:
tf.math.log(
    tf.reduce_max(model(states) * tf.one_hot(actions, 2), axis=1)
)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-0.24426115, -1.4694961 , -0.25372857, -0.2343033 , -1.5986106 ,
       -0.22768767, -1.4827293 , -1.5993652 , -1.48944   , -0.2445018 ],
      dtype=float32)>

In [23]:
model(states)

<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[-0.6592313 ,  0.53607464],
       [-0.7011502 ,  0.7171604 ],
       [-0.8317009 ,  0.59882075],
       [-0.6555121 ,  0.740333  ],
       [-0.83310086,  0.47994095],
       [-0.899259  ,  0.4118735 ],
       [-0.8838528 ,  0.6024823 ],
       [-0.88740665,  0.41205296],
       [-0.8829417 ,  0.5492847 ],
       [-0.69580525,  0.5764605 ]], dtype=float32)>